[package]
name = "allax"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.8.0"
serde_json = "1.0"
serde = "1.0.126"
serde_derive = "*"